#!/usr/bin/env python3

# Copyright (C) 2020 Konstantin Unruh <freaxmate@protonmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

import sys
import os

def main():
    if len(sys.argv) < 3:
        print("Missing color hex codes")
        return

    legacy_color = sys.argv[1]
    replace_color = sys.argv[2]

    file_list = os.scandir("../data/layout-previews/")

    for filename in file_list:
        print(file_list)
        if filename.name.endswith(".svg"):
           file = open(filename, 'rt')
           print("Edit ", filename.name, "...")
           data = file.read()
           data = data.replace(legacy_color, replace_color)
           file.close()

           file = open(filename, 'wt')
           file.write(data)
           file.close()

           print("Replace ", legacy_color, " with ", replace_color)


if __name__ == "__main__":
    main()
